#' Single-event example dataset
#'
#' A simulated dataset used in the single-event IPCW guided example. It
#' represents a clinical scenario where the event of interest is
#' progression-free survival, the binary treatment covariate `x` distinguishes
#' two treatment arms, and `W2` is an informative censoring covariate
#' (analogous to an ancillary biomarker). Censoring depends on `W2`, making
#' standard Kaplan-Meier and Cox analyses potentially biased.
#'
#' @format A tibble with 500 rows and 5 columns:
#' \describe{
#'   \item{S}{True (latent) event time.}
#'   \item{t}{Observed time (minimum of `S` and the censoring time).}
#'   \item{delta}{Event indicator: 1 = event occurred, 0 = censored.}
#'   \item{x}{Binary treatment indicator: 0 = chemotherapy, 1 = TKI.}
#'   \item{W2}{Continuous covariate that drives informative censoring
#'     (analogous to an ancillary biomarker).}
#' }
#'
#' @details
#' The dataset was generated with the following parameters:
#' \itemize{
#'   \item \eqn{n = 500}, \eqn{\alpha = 0.05}, \eqn{\sigma = 500},
#'     \eqn{\beta = \log(0.25)}, \eqn{\lambda = 0.01}, \eqn{\phi = -5}.
#'   \item \code{set.seed(20240429)}.
#' }
#' See the single-event vignette for the full data-generation code.
#'
#' @source Generated by the authors.
"single_example_dat"


#' Single-event example dataset in IPCW long format
#'
#' The [single_example_dat] dataset converted to counting-process (long) format
#' with IPCW weights appended, as produced by the data-preparation steps in the
#' single-event vignette (or equivalently by [get_ipcw_wgt()]).
#'
#' @format A data frame in long format with one or more rows per subject and
#'   columns including:
#' \describe{
#'   \item{id_nest}{Nested simulation identifier.}
#'   \item{id}{Subject identifier.}
#'   \item{true_time}{True (latent) event time used for simulation diagnostics.}
#'   \item{tstart}{Left endpoint of the time interval.}
#'   \item{tstop}{Right endpoint of the time interval.}
#'   \item{delta}{Event indicator for the current interval.}
#'   \item{censor}{Censoring indicator for the current interval.}
#'   \item{x}{Binary treatment indicator.}
#'   \item{W2}{Ancillary biomarker covariate.}
#'   \item{inv_wgt}{Estimated probability of remaining uncensored (inverse of the weight).}
#'   \item{wgt}{Unstabilized IPCW weight (reciprocal of `inv_wgt`).}
#' }
#'
#' @source Generated by the authors via [get_ipcw_wgt()] applied to
#'   [single_example_dat].
"single_example_ipcw_dat"
