#' Bootstrap log hazard ratios from IPCW Cox models
#'
#' A numeric vector of 500 bootstrap log hazard ratio estimates for the effect
#' of treatment (`x`) on progression-free survival, each obtained by fitting an
#' IPCW-weighted Cox model to one bootstrap sample of `single_example_dat`.
#' Provided as package data to avoid re-running the time-consuming bootstrap
#' in vignettes and examples. Use with [get_boot_pci_se()] and
#' [get_boot_var_se()] to obtain bootstrap-based confidence intervals and
#' variance estimates.
#'
#' @format A numeric vector of length 500.
#'
#' @source Generated by the authors by applying [get_ipcw_boot_se()] to
#'   `single_example_dat` with `B = 500` and `seed = 20240917`, then fitting
#'   [get_ipcw_cox_fit_se()] to each bootstrap sample and extracting `log_hr`.
#' @usage data(cox_boot_lhr)
"cox_boot_lhr"


#' Bootstrap Fine-Gray coefficients from stratified IPCW weights
#'
#' A 500-by-3 matrix of bootstrap log sub-distribution hazard ratio estimates
#' for the effect of baseline PSA quartile (`z1`) on metastasis, each row
#' obtained by fitting a stratified-weight Fine-Gray model to one bootstrap
#' sample of the competing risks guided example data. Provided as package
#' data to avoid re-running the time-consuming bootstrap in vignettes and
#' examples. Use with [get_boot_pci_cr()] to obtain bootstrap-based
#' confidence intervals.
#'
#' @format A numeric matrix with 500 rows (bootstrap replicates) and 3
#'   columns (`z1` levels 1, 2, and 3 vs. the reference level 0).
#'
#' @source Generated by the authors by applying [get_ipcw_boot_cr()] with
#'   `B = 500` and `seed = 20240917` to a competing risks dataset simulated
#'   via `sim_data_cr(n = 500, censoring = "baseline", beta1 = log(1.5),
#'   beta2 = log(2.25), beta3 = log(3.4), p = 0.3)` with `set.seed(9843)`,
#'   then fitting [fg_weighted_cr()] with stratified weights
#'   ([add_fg_weights_cr()] with `strat = "yes"`) to each bootstrap sample and
#'   extracting the coefficient column.
#' @usage data(fg_strat_boot)
"fg_strat_boot"
