#' Bootstrap log hazard ratios from IPCW Cox models
#'
#' A numeric vector of 500 bootstrap log hazard ratio estimates for the effect
#' of treatment (`x`) on progression-free survival, each obtained by fitting an
#' IPCW-weighted Cox model to one bootstrap sample of `single_example_dat`.
#' Provided as package data to avoid re-running the time-consuming bootstrap
#' in vignettes and examples. Use with [get_boot_pci_se()] and
#' [get_boot_var_se()] to obtain bootstrap-based confidence intervals and
#' variance estimates.
#'
#' @format A numeric vector of length 500.
#'
#' @source Generated by the authors by applying [get_ipcw_boot_se()] to
#'   `single_example_dat` with `B = 500` and `seed = 20240917`, then fitting
#'   [get_ipcw_cox_fit_se()] to each bootstrap sample and extracting `log_hr`.
#' @usage data(cox_boot_lhr)
"cox_boot_lhr"
